### PR TITLE
Update webpack peerDep to include ^3.0.0

### PR DESCRIPTION
**Pull request by dhedgecock**
Resolves peer dep warning when using Webpack 3.0+

### CODE REVIEW

**Comment by dhedgecock** [comment]
@alexkuz any chance you can take a look at this?

**Comment by dhedgecock** [comment]
@alexkuz ping?

**Comment by jennydaman** [comment]
@alexkuz do you have time to visit this PR? Should be compatible.

**Comment by dhedgecock** [comment]
I'm closing this to keep my list of open PRs current ¯\_(ツ)_/¯

**Pull request closed without merging**
